apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
      - name: my-daemonset-container
        image: busyboxplus:curl
        command: ["sh", "-c", "while true; do curl http://todoapp-service.mateapp.svc.cluster.local:80; sleep 5; done"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Always